### ISSUE TITLE
16.3.2 Running cookiecutter command returns error traceback (Windows 10)

### ISSUE THREAD

**Issue by captkidd** [feldroy/django-crash-course#232]
(everycheese) C:\Users\PlayerOne\dccp>cookiecutter gh:feldroy/django-crash-starter
Traceback (most recent call last):
  File "C:\Users\PlayerOne\miniconda3\envs\everycheese\Scripts\cookiecutter-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\PlayerOne\miniconda3\envs\everycheese\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\PlayerOne\miniconda3\envs\everycheese\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\PlayerOne\miniconda3\envs\everycheese\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\PlayerOne\miniconda3\envs\everycheese\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\PlayerOne\miniconda3\envs\everycheese\lib\site-packages\cookiecutter\cli.py", line 113, in main
    cookiecutter(
  File "C:\Users\PlayerOne\miniconda3\envs\everycheese\lib\site-packages\cookiecutter\main.py", line 57, in cookiecutter
    repo_dir, cleanup = determine_repo_dir(
  File "C:\Users\PlayerOne\miniconda3\envs\everycheese\lib\site-packages\cookiecutter\repository.py", line 99, in determine_repo_dir
    cloned_repo = clone(
  File "C:\Users\PlayerOne\miniconda3\envs\everycheese\lib\site-packages\cookiecutter\vcs.py", line 78, in clone
    raise VCSNotInstalled(msg)
cookiecutter.exceptions.VCSNotInstalled: 'git' is not installed.

(everycheese) C:\Users\PlayerOne\dccp>

**Comment by quique** [comment]
The traceback says `'git' is not installed`.

I would double-check the git command-line utility is correctly installed (section 1.4).

**Comment by captkidd** [comment]
Thanks quique. Carla sent me info recommending I install gitforwindows instead of github desktop (as per beta para 1.4.1). This fixed the issue I was having allowing me to continue moving forward.

**Comment by pydanny** [comment]
I'm happy you could resolve it! Let us know what else we can do!
