### ISSUE TITLE
python manage.py migrate brings an error

### ISSUE THREAD

**Issue by renequinones** [feldroy/django-crash-course#250]
Hello

I was following the book and in the page 99 once I typed the command "python manage.py migrate" the system gave me the following error:

Traceback (most recent call last):
  File "C:\Users\reneq\.conda\envs\health_engine\lib\site-packages\django\db\backends\base\base.py", line 220, in ensure_connection
    self.connect()
  File "C:\Users\reneq\.conda\envs\health_engine\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\reneq\.conda\envs\health_engine\lib\site-packages\django\db\backends\base\base.py", line 197, in connect
    self.connection = self.get_new_connection(conn_params)
  File "C:\Users\reneq\.conda\envs\health_engine\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\reneq\.conda\envs\health_engine\lib\site-packages\django\db\backends\postgresql\base.py", line 185, in get_new_connection
    connection = Database.connect(**conn_params)
  File "C:\Users\reneq\.conda\envs\health_engine\lib\site-packages\psycopg2\__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: fe_sendauth: no password supplied

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 34, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\reneq\.conda\envs\health_engine\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\reneq\.conda\envs\health_engine\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\reneq\.conda\envs\health_engine\lib\site-packages\django\core\management\base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\reneq\.conda\envs\health_engine\lib\site-packages\django\core\management\base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "C:\Users\reneq\.conda\envs\health_engine\lib\site-packages\django\core\management\base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "C:\Users\reneq\.conda\envs\health_engine\lib\site-packages\django\core\management\commands\migrate.py", line 86, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "C:\Users\reneq\.conda\envs\health_engine\lib\site-packages\django\db\migrations\executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "C:\Users\reneq\.conda\envs\health_engine\lib\site-packages\django\db\migrations\loader.py", line 49, in __init__
    self.build_graph()
  File "C:\Users\reneq\.conda\envs\health_engine\lib\site-packages\django\db\migrations\loader.py", line 212, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "C:\Users\reneq\.conda\envs\health_engine\lib\site-packages\django\db\migrations\recorder.py", line 76, in applied_migrations
    if self.has_table():
  File "C:\Users\reneq\.conda\envs\health_engine\lib\site-packages\django\db\migrations\recorder.py", line 56, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "C:\Users\reneq\.conda\envs\health_engine\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\reneq\.conda\envs\health_engine\lib\site-packages\django\db\backends\base\base.py", line 260, in cursor
    return self._cursor()
  File "C:\Users\reneq\.conda\envs\health_engine\lib\site-packages\django\db\backends\base\base.py", line 236, in _cursor
    self.ensure_connection()
  File "C:\Users\reneq\.conda\envs\health_engine\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\reneq\.conda\envs\health_engine\lib\site-packages\django\db\backends\base\base.py", line 220, in ensure_connection
    self.connect()
  File "C:\Users\reneq\.conda\envs\health_engine\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\reneq\.conda\envs\health_engine\lib\site-packages\django\db\backends\base\base.py", line 220, in ensure_connection
    self.connect()
  File "C:\Users\reneq\.conda\envs\health_engine\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\reneq\.conda\envs\health_engine\lib\site-packages\django\db\backends\base\base.py", line 197, in connect
    self.connection = self.get_new_connection(conn_params)
  File "C:\Users\reneq\.conda\envs\health_engine\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\reneq\.conda\envs\health_engine\lib\site-packages\django\db\backends\postgresql\base.py", line 185, in get_new_connection
    connection = Database.connect(**conn_params)
  File "C:\Users\reneq\.conda\envs\health_engine\lib\site-packages\psycopg2\__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: fe_sendauth: no password supplied

I tried several ways to fix it and it nothing worked. So please let me know if you find a solution.

Thanks beforehand, 
Best regards, 
Rene

## Greetings! 

Hello! As a reader, you're encouraged to submit bug reports to us for errors that you find. In turn we will give you credit for your contributions in not just the e-book but also in the print paperback and online publicly on the web. This is your opportunity to have your name in one of our books as a contributor, which you are then welcome to add to your resume and LinkedIn profile. (Note: TODOs are markers to to let you know we are going to expand an area, so reporting them during the ALPHA and BETA period **doesn't** qualify as an attributable item.)

## Location within the Book

* Chapter or Appendix:
* Section:
* Subsection:

Hint: Page numbers change all the time. The best way to report an issue is by chapter, section, and subsection numbers.

## Description 

> If grammar, enter problematic text here, otherwise delete this line.

```
If code-related, enter it within these backticks. Otherwise, delete this segment.
```

**Comment by danjaruss** [comment]
Receiving this same error.
On a windows machine.

**Comment by snowpilgrim** [comment]
I am also experiencing this.
Thanks in advance.

**Comment by contadorpl** [comment]
is author responding?

**Comment by contadorpl** [comment]
> I am also experiencing this.
> Thanks in advance.

Have you managed it?

**Comment by pydanny** [comment]
This is a PostgreSQL error that we haven't been able to fix on Windows for everyone because neither Microsoft or EnterpriseDB support PostgreSQL yet, even on WSL2.

**Comment by pydanny** [comment]
For now, the solution is to re-run django-crash-starter so the project uses SQLite. When PostgreSQL is reliable on Windows, we'll help convert your projects to it.
