### ISSUE TITLE
psycopg2.OperationalError: fe_sendauth: no password supplied

### ISSUE THREAD

**Issue by Ah8Huang** [feldroy/django-crash-course#357]
Hi, 

I’ve been reading the book “Django Crash Course Covers Python 3.8 and Django 3.x” these days.   I met with a problem when I come to the second django project Eveycheese. 

When  I run cammand -- python manage.py migrate- and  it failed, showing:”  psycopg2.OperationalError: fe_sendauth: no password supplied” and django.db.utils.OperationalError: fe_sendauth: no password supplied”

I tried to google for the solutions ,but I found nothing could fix it. I hope someone have some good ideas for fixing these problems.

By the way, I am using Windows 10 pro x64 Ver 2004, Python 3.8, Django 3x ,PostgreSQL 12 and VS Code 1.48.

The following messages are for your reference:
-------------------------------------------------
(everycheese) PS C:\Users\hxd66\project5566\everycheese>  **python manage.py makemigrations**
Traceback (most recent call last):
  File "C:\Users\hxd66\miniconda3\envs\everycheese\lib\site-packages\django\db\backends\base\base.py", line 220, in ensure_connection
    self.connect()
  File "C:\Users\hxd66\miniconda3\envs\everycheese\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\hxd66\miniconda3\envs\everycheese\lib\site-packages\django\db\backends\base\base.py", line 197, in connect
    self.connection = self.get_new_connection(conn_params)
  File "C:\Users\hxd66\miniconda3\envs\everycheese\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\hxd66\miniconda3\envs\everycheese\lib\site-packages\django\db\backends\postgresql\base.py", line 185, in get_new_connection
    connection = Database.connect(**conn_params)
  File "C:\Users\hxd66\miniconda3\envs\everycheese\lib\site-packages\psycopg2\__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
**psycopg2.OperationalError**

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 35, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\hxd66\miniconda3\envs\everycheese\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\hxd66\miniconda3\envs\everycheese\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\hxd66\miniconda3\envs\everycheese\lib\site-packages\django\core\management\base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\hxd66\miniconda3\envs\everycheese\lib\site-packages\django\core\management\base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "C:\Users\hxd66\miniconda3\envs\everycheese\lib\site-packages\django\core\management\base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "C:\Users\hxd66\miniconda3\envs\everycheese\lib\site-packages\django\core\management\commands\makemigrations.py", line 101, in handle
    loader.check_consistent_history(connection)
  File "C:\Users\hxd66\miniconda3\envs\everycheese\lib\site-packages\django\db\migrations\loader.py", line 283, in check_consistent_history
    applied = recorder.applied_migrations()
  File "C:\Users\hxd66\miniconda3\envs\everycheese\lib\site-packages\django\db\migrations\recorder.py", line 76, in applied_migrations
    if self.has_table():
  File "C:\Users\hxd66\miniconda3\envs\everycheese\lib\site-packages\django\db\migrations\recorder.py", line 56, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "C:\Users\hxd66\miniconda3\envs\everycheese\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\hxd66\miniconda3\envs\everycheese\lib\site-packages\django\db\backends\base\base.py", line 260, in cursor
    return self._cursor()
  File "C:\Users\hxd66\miniconda3\envs\everycheese\lib\site-packages\django\db\backends\base\base.py", line 236, in _cursor
    self.ensure_connection()
  File "C:\Users\hxd66\miniconda3\envs\everycheese\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\hxd66\miniconda3\envs\everycheese\lib\site-packages\django\db\backends\base\base.py", line 220, in ensure_connection
    self.connect()
  File "C:\Users\hxd66\miniconda3\envs\everycheese\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\hxd66\miniconda3\envs\everycheese\lib\site-packages\django\db\backends\base\base.py", line 220, in ensure_connection
    self.connect()
  File "C:\Users\hxd66\miniconda3\envs\everycheese\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\hxd66\miniconda3\envs\everycheese\lib\site-packages\django\db\backends\base\base.py", line 197, in connect
    self.connection = self.get_new_connection(conn_params)
  File "C:\Users\hxd66\miniconda3\envs\everycheese\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\hxd66\miniconda3\envs\everycheese\lib\site-packages\django\db\backends\postgresql\base.py", line 185, in get_new_connection
    connection = Database.connect(**conn_params)
  File "C:\Users\hxd66\miniconda3\envs\everycheese\lib\site-packages\psycopg2\__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
**django.db.utils.OperationalError**

Thank you.
Huang

**Comment by pydanny** [comment]
We do not have a record of you purchasing the book. If you have purchased the book, reopen this ticket while also  providing your order number.
